### ISSUE TITLE
Why does dnscap not read only dns query traffic?

### ISSUE THREAD

**Issue by IDJack** [DNS-OARC/dnscap#114]
I meet a problem when I use dnscap.
I collect the dns traffic from the local dns server in our university and save as pcap format. The dns traffic is consists of two parts: 1 the traffic between the local dns and the hosts in our university; 2, the traffic between the local dns and upper dns. I focus on analysing the traffic 1.
However, I find that there are some dns query packets which don't have the corresponding response packet. For example, the third packet. 
![image](https://user-images.githubusercontent.com/14247115/33918262-615b0582-dfed-11e7-9f58-872f112f6e5b.png)

When I use dnscap to parse the dns traffic, I find the dnscap just read those dns traffic which have query and response both, it does not read the dns query packets which don't have the corresponding response packet(like packet3).
I use the option (-s i)，but it output nothing.

How can i use dnscap to read only dns query packets which don't have the corresponding response packets? Thank you!

**The file test.pcap[test.pcap.zip](https://github.com/DNS-OARC/dnscap/files/1553919/test.pcap.zip) is the only dns query traffic, it output nothing when I use 'dnscap -r test.pcap -g -', why?**

**Comment by jelu** [comment]
What version of `dnscap` are you using?

What platform are you running on?

How did you capture the traffic?

What does `tcpdump -n -v -r test.pcap` output?

**Comment by IDJack** [comment]
1. I use _dnscap1.5.1_

2. _ubuntu16.04_

3. I use _tcpdump_ to capture all traffic of the local DNS server(suppose its IP is x.x.x.x) in my university and save as pcap format. 
I want to exact the dns query traffic. When I use  **"tcpdump -r xxx.pcap -w dns_query.pcap 'dst host x.x.x.x and dst port 53' "**, I find there is nothing in the output. However, when I use **" tshark  -r xxx.pcap -w dns_query.pcap -Y "dns and ( (ip.dst==x.x.x.x and udp.dstport==53)"** " , it can exact the dns query traffic. I don't know why.

4. tcpdump -n -v -r test.pcap output
![image](https://user-images.githubusercontent.com/14247115/33926701-20edc30e-e01a-11e7-9fc4-a6c5de9ed552.png)

**Comment by jelu** [comment]
Your traffic is captured on a VLAN, use `dnscap -r test.pcap -g -l 30` and `tcpdump -n -v -r test.pcap vlan 30 and port 53`.

**Comment by IDJack** [comment]
Some traffic is captured on a VLAN, while some traffic is not. How to read all traffic?

no VLAN
![20171213172504](https://user-images.githubusercontent.com/14247115/33931323-9dda83f6-e02a-11e7-9696-bfb78eb629eb.png)

VLAN
![image](https://user-images.githubusercontent.com/14247115/33931358-b448cfc6-e02a-11e7-9b3f-57f2d694fe75.png)

**Comment by jelu** [comment]
Try selecting all VLANs, check the man-page for option `-l` and `-L`.
