### ISSUE TITLE
dns Message too long?

### ISSUE THREAD

**Issue by IDJack** [DNS-OARC/dnscap#127]
I use -g to ouput presentation form of DNS traffic. But I find some information is 'dns Message too long'. I can not get detail information, such as domain. How can I access detail information of every dns query or response, not just 'dns Message too long'

**Comment by jelu** [comment]
That looks like an error from libresolve's ns_initparse(), probably an
invalid, faulty or broken DNS message.

Can you share the captured traffic?

**Comment by IDJack** [comment]
This is file is the sample of the traffic. 
[dnsMessageLongExample.pcap.zip](https://github.com/DNS-OARC/dnscap/files/1584685/dnsMessageLongExample.pcap.zip)

**Comment by jelu** [comment]
This is due to padded data after the DNS, a good example of a badly implemented DNS client in the TP-Link. It has a fixed buffer for the DNS packet and sends all of the buffer, even if the question is smaller.

Will be fixed in v1.7.1.
