### ISSUE TITLE
How can I judge a RR is Answer RR or Authority RR or  Additional RR?

### ISSUE THREAD

**Issue by IDJack** [DNS-OARC/dnscap#138]
I use -g to ouput presentation form of DNS traffic. For example, the RR(1 sogou.com,IN,SOA,372,ns1.sogou.com,dnsadmin.sogou-inc.com,1517217171,300,180,1209600,180 0). How can I judge which role of this RR is? Answer RR or Authority RR or  Additional RR?
![20180129220946](https://user-images.githubusercontent.com/14247115/35514466-3a851032-0541-11e8-9677-b358fbbe14cc.png)

This RR may be a Authority RR and  Additional RR.

In fact, I use wireshark to analyze the traffic, and I find this RR is a Authority RR, and I find the number of answer RRs is 0, the number of authority RRs is 1 and the number of additional RR is 0.

If I don't use wireshark, just use -g of dnscap, How can I judge a RR is Answer RR or Authority RR or  Additional RR? How can I get the number of Answer RR or Authority RR or  Additional RR?

**Comment by jelu** [comment]
It is always in the order of questions, answers, authority and additional (as it is in DNS).

The number in front says how many of each there is, as described in the man-page:
```
Next are the 4 sections of the DNS, each section is prefixed
by the number of records and each record and section are sep‐
arated by space.  Below are a few example, first is just a
query, second has just one answer and the last has also
authority and additional records.

1 example.com,IN,A 0 0 0

1 example.com,IN,A \
1 example.com,IN,A,47,127.0.0.1 0 0

1 example.com,IN,A \
1 example.com,IN,A,263,127.0.0.1 \
4 example.com,IN,NS,157794,ns1.example.com \
example.com,IN,NS,157794,ns4.example.com \
example.com,IN,NS,157794,ns3.example.com \
example.com,IN,NS,157794,ns2.example.com \
4 ns2.example.com,IN,A,157794,127.0.0.1 \
ns1.example.com,IN,A,331796,127.0.0.1 \
ns3.example.com,IN,A,157794,127.0.0.1 \
ns4.example.com,IN,A,157794,127.0.0.1
```

**Comment by jelu** [comment]
In your picture the full RR is:
```
1 config.pinyin.sogou.com,IN,AAAA 0 \
1 sogou.com,IN,SOA,372,ns1.sogou.com,dnsadmin.sogou-inc.com,1517217171,300,180,1209600,180 0
```

First argument is the number of questions:
```
>>> 1 <<< config.pinyin.sogou.com,IN,AAAA 0 \
1 sogou.com,IN,SOA,372,ns1.sogou.com,dnsadmin.sogou-inc.com,1517217171,300,180,1209600,180 0
```

Second argument is the question:
```
1 >>> config.pinyin.sogou.com,IN,AAAA <<< 0 \
1 sogou.com,IN,SOA,372,ns1.sogou.com,dnsadmin.sogou-inc.com,1517217171,300,180,1209600,180 0
```

Third argument is the number of answers:
```
1 config.pinyin.sogou.com,IN,AAAA >>> 0 <<< \
1 sogou.com,IN,SOA,372,ns1.sogou.com,dnsadmin.sogou-inc.com,1517217171,300,180,1209600,180 0
```

As there are 0 answers there are no answers.

Fourth argument is the number of authorities:

```
1 config.pinyin.sogou.com,IN,AAAA 0 \
>>> 1 <<< sogou.com,IN,SOA,372,ns1.sogou.com,dnsadmin.sogou-inc.com,1517217171,300,180,1209600,180 0
```

Fifth argument is the authority, just one as fourth argument specified:
```
1 config.pinyin.sogou.com,IN,AAAA 0 \
1 >>> sogou.com,IN,SOA,372,ns1.sogou.com,dnsadmin.sogou-inc.com,1517217171,300,180,1209600,180 <<< 0
```

Sixth argument is the number of additional:
```
1 config.pinyin.sogou.com,IN,AAAA 0 \
1 sogou.com,IN,SOA,372,ns1.sogou.com,dnsadmin.sogou-inc.com,1517217171,300,180,1209600,180 >>> 0 <<<
```

As there are 0 additional there are no additional.

**Comment by IDJack** [comment]
Is the the number of questions always equal to 1?

**Comment by jelu** [comment]
The DNS protocol allows for more but most clients and servers does not look beyond the first question.
