### ISSUE TITLE
How can I extract information from DNS packet?

### ISSUE THREAD

**Issue by IDJack** [DNS-OARC/dnscap#139]
I need to extract information from DNS traffic(pcap format), such as srcip, dstip, flags, rcode, domain, RRs and so on.

I use -g option of dnscap to output text format of DNS traffic and then use Python and regular expression to process the text to extract the information. 

Are there any other method to extract information from DNS traffic(pcap format)? Can I extract the information from DNS traffic directly and don't transfer to text format?

**Comment by jelu** [comment]
With `dnscap` you can dump the DNS traffic with `-g` or write your own C plugin, check `plugins/template/` or `plugins/txtout/`.
