### ISSUE TITLE
Incomplete "sources" file generated by "rssm" plugin

### ISSUE THREAD

**Issue by aabdnn** [DNS-OARC/dnscap#140]
We run dnscap on every instance of K-root, and we activate the "rssm" and "rzkeychange" plugins. We have "-t 3600" defined, so dnscap dumps "sources" and "rssm" files every hour. One on of our servers, I restarted dnscap (TERM signal, followed by starting it again). This is a normal thing to do. However, the sources file that it dumped, contained this line at the end:

2804:7f7:e186:2917:20d:b9

Notice this this is not a valid IPv6 address, and this was caught by our processing script. Notice also that the address is missing a following field, which should have been a count of the number of times the address was seen.

It looks to me like the file is incomplete, and is probably caused by a missing "flush" on the file, or some other race condition.

**Comment by jelu** [comment]
How exactly do you restart it? `kill` or some system init stuff?

There is no missing flush, file is opened, written to and closed in the same function so it should be whole. But if your using some system init stuff that might send a second kill to it because it's taking some time to write the sources, then it will probably die in the middle.

**Comment by aabdnn** [comment]
We run dnscap under systemd. To stop it, we run "systemctl stop dnscap". This makes systemd send it a TERM signal. If dnscap does not exit after 90s, then systemd will send it a KILL signal, but I have checked, and this is not the case, because dnscap does exit quite quickly, within just a couple of seconds. So I don't think it is a problem of running it under systemd.

**Comment by jelu** [comment]
How many sources do you get in a complete file?

**Comment by aabdnn** [comment]
On this server, the number varies from about 15,600 to 26,000 unique sources.

**Comment by aabdnn** [comment]
FYI, here's what systemd shows for the restart:

```
Jan 29 14:49:48 ns1.uy-mvd.k.ripe.net systemd[1]: Stopping dnscap service...
Jan 29 14:49:48 ns1.uy-mvd.k.ripe.net dnscap[100057]: dnscap: signalled break
Jan 29 14:49:48 ns1.uy-mvd.k.ripe.net dnscap[100057]: 1517234400-2988-2778197-5664-288011-510184-1-55-42.ns1.uy-mvd.k-root.ksk-rollover.research.icann.org
Jan 29 14:49:48 ns1.uy-mvd.k.ripe.net systemd[1]: Started dnscap service.
Jan 29 14:49:48 ns1.uy-mvd.k.ripe.net systemd[1]: Starting dnscap service...
Jan 29 14:49:48 ns1.uy-mvd.k.ripe.net dnscap[146290]: Testing reachability of zone 'ksk-rollover.research.icann.org'
Jan 29 14:49:48 ns1.uy-mvd.k.ripe.net dnscap[146290]: ksk-rollover.research.icann.org
Jan 29 14:49:49 ns1.uy-mvd.k.ripe.net dnscap[146290]: Success.
Jan 29 14:49:49 ns1.uy-mvd.k.ripe.net dnscap[146290]: ts-elapsed-tot-dnskey-tcp-tc-unreachfrag-texcfrag-texcttl.ns1.uy-mvd.k-root.ksk-rollover.research.icann.or
Jan 29 15:00:00 ns1.uy-mvd.k.ripe.net dnscap[146290]: 1517237388-612-607354-1304-94765-113820-0-16-6.ns1.uy-mvd.k-root.ksk-rollover.research.icann.org
```

As you can see, there was no KILL signal involved, and dnscap did not linger for too long or anything.

**Comment by jelu** [comment]
Is this problem consistent?

Can you apply a patch to dnscap for just that server?

**Comment by aabdnn** [comment]
No, this doesn't appear to be a consistent problem. I saw it today for the first time in ages. I've seen it once before, but I must have forgotten to open a bug report then. I can't apply a patch just for this server. I'm using the dnscap RPM that you've built.

**Comment by jelu** [comment]
I can build a new RPM for you, what dist are you running?

**Comment by jelu** [comment]
Reason it's quick to exit is because RSSM double `fork()` to not stall main, this may be a problem if signals arrive to the forked processes.

**Comment by aabdnn** [comment]
Ah, so systemd sends a TERM signal to the entire cgroup by default, which means it could send TERM to the forked rssm child before it has finished writing its file. This is easy to fix in systemd, by asking it to send TERM only to the main PID.

**Comment by aabdnn** [comment]
We run CentOS 7, by the way.

**Comment by jelu** [comment]
I've added some more information output (#141) and an option to disable forking on close, something you want me to build a RPM for you?

**Comment by aabdnn** [comment]
Well, I just added "KillMode=process" to our systemd unit files, to prevent systemd from sending TERM to the child processes. I think that's sufficient for our purposes. Your extra options may still be useful, but I don't feel the need to update our copy of dnscap just yet, because this is a very rare event.

**Comment by jelu** [comment]
OK sounds like you found it, especially since it's rare (need to time that TERM within the 3600 seconds interval). Hope it works and be sure to reopen this issue if it occurs again.

**Comment by elico** [comment]
@jelu Where can I get the RPM mentioned by @aabdnn ? 
 
> No, this doesn't appear to be a consistent problem. I saw it today for the first time in ages. I've seen it once before, but I must have forgotten to open a bug report then. I can't apply a patch just for this server. I'm using the dnscap RPM that you've built.

**Comment by jelu** [comment]
@elico https://dev.dns-oarc.net/packages/

**Comment by elico** [comment]
@jelu Thanks!
