### ISSUE TITLE
Closing a plug-in after capturing N packets

### ISSUE THREAD

**Issue by huitema** [DNS-OARC/dnscap#161]
I am surprised by the behavior of DNSCAP when specifying both the "-c" and "-P" option. In an experiment, I am specifying:
~~~
   dnscap -c 1000 -P libmyplugin.so
~~~
My naive expectation was that DNSCAp would pass 10 packets to the plugin, then close the capture session. Instead, it appears that DNSCAP is capturing 1000 packets, then another 1000, ad infinitum. 

Is there a way to actually stop the session after 1000 packets?

**Comment by jelu** [comment]
This is all expected behavior of `-c`, `-t` and options like them, per man-page for `-c lim`:

> By default, dnscap will close its packet dump file only when
> interrupted.  A dump file size, measured in packets, can be
> specified with the -c option.  **If the packet dump file is
> standard output, then after closing this file, dnscap exits.**
> This option is inclusive with -t.

And per `-?`:
> -c <lim> close dump **or** exit every/after <lim> pkts

There is currently no option to get the stdout behavior for plugins but I will keep this issue opened in case I get time to add an extended option that changes the behavior.

**Comment by huitema** [comment]
Is there a way for the plug-in to force the capture to stop?

**Comment by RoyArends** [comment]
> On 22 Mar 2018, at 18:41, Christian Huitema <notifications@github.com> wrote:
> 
> Is there a way for the plug-in to force the capture to stop?

Invoke it twice, and use pipes:

So instead of:

dnscap -i eth0 -c 1000 -P libmyplugin.so 

You can use:

dnscap -i eth0 -c 1000 -w - | dnscap -r - -P libmyplugin.so

The first invocation of dnscap will take the first 1000 packets on the wire and streams it to standard-out. The second invocation takes all the packets from stdin and streams those to libmyplugin.so

Hope this helps,

Roy

**Comment by huitema** [comment]
@RoyArends yes, that works.
