### ISSUE TITLE
Feature request: match by query type

### ISSUE THREAD

**Issue by wessels** [DNS-OARC/dnscap#167]
dnscap can already select messages based on: opcode, rcode, name, src/dst.  

I would find it useful to also be able to select based on query type.

**Comment by jelu** [comment]
Would something in the line of this feel logic/functional?
```
  -q type    Capture only messages of designated QTYPE (integer).  Default is all.
  -Q type    Capture only messages NOT of designated QTYPE (integer).  Can not be used with -q.
```
We can add textual support later.

**Comment by wessels** [comment]
Yes that would work, and is similar to how matching on name and address is handled.

**Comment by jelu** [comment]
Sorry it took so long!
