### ISSUE TITLE
How does -w calculates seconds when giving name to file

### ISSUE THREAD

**Issue by wsihaidr** [DNS-OARC/dnscap#206]
I am using -t flag to periodically create pcap files every 60 seconds.  The files created has name "base.Date.seconds.microseconds.pcap"
As mentioned in man page the w flag generates the name as base, seconds and microseconds. I want to know how the seconds are calculated. Cause when i convert seconds to hh mm ss it goes above 1 day.

**Comment by jelu** [comment]
The man-page is wrong, it's `$base.$date.$hours$minutes$seconds.$microseconds`.

**Comment by jelu** [comment]
Thanks for the report, it's fixed now and will be in the next release.

**Comment by wsihaidr** [comment]
I am trying to generate pcap files periodically each 60 seconds. But the generated files does not have time difference of 60 seconds exactly.
