### ISSUE TITLE
Extend privilege dropping implementation to set correct supplemental groups

### ISSUE THREAD

**Issue by theopolis** [DNS-OARC/dnscap#208]
Hello, It looks like the code does a lot of work to drop privileges, which is great! https://github.com/DNS-OARC/dnscap/blob/develop/src/daemon.c#L40

I saw that the code is not attempting to drop (or set) supplementary groups via `setgroups` (easy but not ideal) or `initgroups` (more correct but will need to check for method availability in AC). If the process is run as root and retains root's supplemental groups this can have security impact.

It looks like the initial implementation of privilege dropping is here https://github.com/DNS-OARC/dnscap/commit/555b73cf6c8b9111c251c5d20fc5ed78f8e62049. Is anyone interested in adding a bit more to set the correct supplemental groups with `initgroups`?

Heads up that  have not tested dnscap, I'm only browsing the code.

**Comment by jelu** [comment]
I'm not sure who you are asking here, maybe this question should go to the [mailing list](https://lists.dns-oarc.net/mailman/listinfo/dnscap-users).

If you have a patch/pull request that enhance security then I'll happily try and merge it :)
