### ISSUE TITLE
t flag does not generate files exactly after the given seconds

### ISSUE THREAD

**Issue by wsihaidr** [DNS-OARC/dnscap#209]
I am trying to generate pcap files periodically each 10 seconds. I am using following command: 
`dnscap -w test -W .pcap -t 10`
But there is difference of 11 or 12 seconds between the files.

**Comment by raybellis** [comment]
What is your packet rate?   AIUI, dnscap will only trigger a file roll at the moment a packet is received because rolls are handled by the packet processing loop and not asynchronously.   If no packet is received at the "scheduled" roll time the roll will be delayed.
