### ISSUE TITLE
Undefined symbols for architecture x86_64:  "_be16toh" and "_be32toh" on macOS

### ISSUE THREAD

**Issue by vollkommenheit** [DNS-OARC/dnscap#241]
I last built dnscap from the git source code successfully in early Nov. Today, the same build process errored out with the following:
> libtool: link: gcc -I. -I.. -I/usr/local/include -I/usr/local/include -g -O2 -O3 -march=native -flto -o dnscap args.o assert.o bpft.o daemon.o dnscap.o dump_cbor.o dump_cds.o dump_dns.o dumper.o endpoint.o hashtbl.o iaddr.o log.o network.o options.o pcaps.o sig.o tcpstate.o tcpreasm.o memzero.o pcap-thread/pcap_thread.o pcap-thread/pcap_thread_ext_frag.o  -L/usr/local/lib /usr/local/lib/libldns.dylib -lcrypto -lz -ldl -lpcap
Undefined symbols for architecture x86_64:
  "_be16toh", referenced from:
      _dump_dns_sect in dump_dns.o
      _dl_pkt in network.o
  "_be32toh", referenced from:
      _dl_pkt in network.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [dnscap] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

The following post points to the fix, for macOS:
https://github.com/fluent/fluent-bit/issues/1561#issuecomment-530342273
In addition, one of the links referenced by the above points to possible endian issue and fix for Windows:
https://github.com/zeromq/zmqpp/issues/164

**Comment by vollkommenheit** [comment]
It compiles successfully, after dropping https://gist.github.com/panzi/6856583 in both ./src/dump_dns.c and ./src/network.c

**Comment by jelu** [comment]
I will look at this once I'm back from holiday in January.

If you depend on dnscap you should not use the development code, and should probably get the tarballs of the released versions instead.

**Comment by vollkommenheit** [comment]
@jelu, of course. I don't depend on dnscap,  just for personal networking pursuits.

**Comment by jelu** [comment]
@vollkommenheit Can you try again with the latest develop branch?

**Comment by vollkommenheit** [comment]
> @vollkommenheit Can you try again with the latest develop branch?

All good now; no errors nor warnings anymore. Thanks.

**Comment by jelu** [comment]
@vollkommenheit Great! Thanks for checking as I don't have access to macOS.
