### ISSUE TITLE
Feature proposal: ability to anonymise EDNS Client Subnet

### ISSUE THREAD

**Issue by pspacek** [DNS-OARC/dnscap#245]
As far as I can tell current anonymization plugins do not anonymise ECS metadata in EDNS payload. This poses problem when anonymizing data from public resolvers (where ECS is more common).

Proposal here is to run anonymization plugins on IP address part of ECS and keep scope/prefix length information as they were. I think it should work if a prefix-preserving anonymization plugin is used.

**Comment by wessels** [comment]
I would like to see this feature as well.

**Comment by jelu** [comment]
How about this, took code from `dsc` to parse and added `-E` to mask:
```
jerry@153c86bdfdd7:~/dnscap/build$ src/dnscap -g -r ~/dsc/src/test/edns.pcap -P plugins/anonmask/.libs/anonmask.so -4 8 2>&1 | grep ECS
	1 .,4096,4096,0,edns0[len=23,UDP=4096,ver=0,rcode=0,DO=0,z=0],edns0opt[ECS,family=1,source=24,scope=0,addr=172.17.0.0],edns0opt[code=10,codelen=8]
	.,1232,1232,0,edns0[len=39,UDP=1232,ver=0,rcode=0,DO=0,z=0],edns0opt[code=10,codelen=24],edns0opt[ECS,family=1,source=24,scope=0,addr=172.17.0.0]

jerry@153c86bdfdd7:~/dnscap/build$ src/dnscap -g -r ~/dsc/src/test/edns.pcap -P plugins/anonmask/.libs/anonmask.so -4 8 -E 2>&1 | grep ECS
	1 .,4096,4096,0,edns0[len=23,UDP=4096,ver=0,rcode=0,DO=0,z=0],edns0opt[ECS,family=1,source=24,scope=0,addr=172.0.0.0],edns0opt[code=10,codelen=8]
	.,1232,1232,0,edns0[len=39,UDP=1232,ver=0,rcode=0,DO=0,z=0],edns0opt[code=10,codelen=24],edns0opt[ECS,family=1,source=24,scope=0,addr=172.0.0.0]
```

**Comment by pspacek** [comment]
I don't see how exactly the -E works, but generally I think it might be useful to use different plugins for EDNS client subnet vs. regular source IPs. For ECS I would like to use something which keeps subnet : anon subnet mapping. For source IP care only about 1:1 mapping.

**Comment by jelu** [comment]
@pspacek it's hard to see but:
```
anonmask.so -4 8
  addr=172.17.0.0

anonmask.so -4 8 -E
  addr=172.0.0.0
```

I don't want to duplicate ALL anonymization plugins just for ECS and you can chain the same plugin multiple times.

I can add `-e` and `-E`, so that `-e` will also anonymize ECS and `-E` will only anonymize ECS, then you can select what to anonymize or chain two of the same plugin to have different masks on src/dst and ECS.
