### ISSUE TITLE
Add a pointer to this repo in -?

### ISSUE THREAD

**Issue by paulehoffman** [DNS-OARC/dnscap#259]
While `dnscap -?` is dumping out the extended help, it would be useful to some users to know where the GitHub repo is. Proposal: add to the bottom:
`GitHub repo: https://github.com/DNS-OARC/dnscap`

**Comment by jelu** [comment]
The URL (and more info) is already in the man-page, isn't that enough?

**Comment by paulehoffman** [comment]
It might not be enough for people who build from source to get the binary but not have easy access to the man pages (such as using `--prefix=/home/someone/LocalStuff`), which is my current use case.

**Comment by jelu** [comment]
If you compile from source you got the source from somewhere, so it's
location should already be known. Or?

I don't follow what problem would be solved by displaying the repository at
the bottom of -?, can you explain more?

**Comment by paulehoffman** [comment]
If I don't have access to the man page because I compiled from source into a path that is not in MANPATH, I might not know how to find out more about dnscap.

I admit this might be kind of an edge case. :-)

**Comment by jelu** [comment]
> If I don't have access to the man page because I compiled from source into a path that is not in MANPATH, I might not know how to find out more about dnscap.

You can set your own `MANPATH` or use `man -M <path>`, or even just man the generated file `man src/dnscap/src/dnscap.1`.

I'm still a bit baffled at why the repository URL would be helpful for some users when you already have the source, what information are you looking for?

**Comment by paulehoffman** [comment]
I think I over-thought this, and it really isn't this important. Closing.
