### ISSUE TITLE
Unable to drop GID to nobody, exiting.

### ISSUE THREAD

**Issue by wessels** [DNS-OARC/dnscap#26]
dnscap tries, and fails, to call setresgid() et al when it doesn't need to.

$ dnscap -r foo.pcap -g
Unable to drop GID to nobody, exiting.

**Comment by jelu** [comment]
I would like to just change the behavior so that if you do not run it as background process it won't try this but that is a breaking change.  What do you think with `-N` to not drop privs and then add to the warning message (if you only do offline pcaps) that you can try and run with `-N` also?

**Comment by wessels** [comment]
I was thinking maybe it should not call drop_privileges() when getuid() != 0.

Or if getuid() != 0 then maybe setresgid etc failures are silently ignored?

A third alternative would be to skip drop_privileges() when reading offline pcaps.
