### ISSUE TITLE
Feature request - support writing a PID file

### ISSUE THREAD

**Issue by raybellis** [DNS-OARC/dnscap#267]
When running as a daemon it would be very useful if dnscap were to write out a PID file that can be used by `rc` scripts for process management without needing to use an external supervisor script such as FreeBSD's `/usr/sbin/daemon`.

**Comment by jelu** [comment]
@raybellis can you test this branch? https://github.com/jelu/dnscap/tree/pid-file

**Comment by raybellis** [comment]
Thanks Jerry - it make take a few days to test this.  In particular I need to check whether the (strictly correct) behaviour of not deleting the PID file at exit causes an issues with FreeBSD's standard `rc` files.

**Comment by raybellis** [comment]
It works - the FreeBSD `service` helper script appears to have no problem with the PID file being left behind after the daemon has exited.

Thanks Jerry!

**Comment by jelu** [comment]
:+1: I'll make a release once I've had time to look at the other issue we talked about, might be late Aug.
