### ISSUE TITLE
Memory usage on FreeBSD

### ISSUE THREAD

**Issue by FerdinandGold** [DNS-OARC/dnscap#290]
I had left dnscap running over the weekend, filtering for a certain string in queries with -x. This Monday I noticed dnscap had crashed due to an out of memory error:

```
swap_pager: out of swap space
swp_pager_getswapspace(25): failed
pid 71937 (dnscap), jid 0, uid 65534, was killed: failed to reclaim memory
```

I'm using the following invocation and see a steady rise in memory consumption:

`nobody   77564    0.1 10.1 1746348 1678128  3  S+   08:34         0:34.05 dnscap -i igb0 -w filr -W .dump -t 3600 -si -x filr4*
`

Is this normal and to be expected? It seems rather odd to me. Running version 2.1.1 here.

**Comment by jelu** [comment]
No, it's not normal.

Can you leave it running for 24h without `-x` to see if that's leaking while I look at the code?

**Comment by FerdinandGold** [comment]
I need the `-x` option for debugging a certain problem, but I just started a second invocation without the option to see if this process grows in size as well.

**Comment by jelu** [comment]
It would be great if you can capture a lot of data that is causing this issue because `-x` is using LDNS and if your under some kind of attack there might be parsing bugs in LDNS that is leaking data. It also make it easier to run `valgrind` and similar tools on the set of data to detect the leak and verify the fix.

**Comment by jelu** [comment]
@FerdinandGold can you also paste exactly the command line your running?

**Comment by jelu** [comment]
> It would be great if you can capture a lot of data that is causing this issue because -x is using LDNS and if your under some kind of attack there might be parsing bugs in LDNS that is leaking data. It also make it easier to run valgrind and similar tools on the set of data to detect the leak and verify the fix.

Never mind, my own test just finished and indeed `-x` is leaking. Will fix as soon as possible!

**Comment by FerdinandGold** [comment]
Yeah the leak clearly only shows with the `-x` switch

```
nobody   77564    0.1 23.4 4167084 3886040  3  S+   08:34         1:19.28 dnscap -i igb0 -w filr -W .dump -t 3600 -si -x filr4*
nobody   80930    0.0  0.0   29100    7536  4  S+   10:45         0:07.88 dnscap -i igb0 -w filr -W .dump -t 3600 -si
```

Thank you for looking into this!

**Comment by jelu** [comment]
@FerdinandGold please compile and test the develop branch

**Comment by FerdinandGold** [comment]
@jelu running `88edf80` now, seems to do fine so far. 👍
