### ISSUE TITLE
Does dnscap 2.2.0 still support ipv6

### ISSUE THREAD

**Issue by sujiacong** [DNS-OARC/dnscap#303]
Does dnscap 2.2.0 still support ipv6? 
I don’t see the parsing demerits for printing ipv6 in my environment.

**Comment by jelu** [comment]
Yes, nothing has change w.r.t. that.

What's the issue?

**Comment by jelu** [comment]
Feel free to reopen the issue with a description of the problem or contact me on our [Mattermost](https://chat.dns-oarc.net/community/channels/oarc-software)
