### ISSUE TITLE
error: variable has incomplete type 'my_bpftimeval' (aka 'struct timeval')

### ISSUE THREAD

**Issue by vollkommenheit** [DNS-OARC/dnscap#35]
Getting this error with latest source:

...
depbase=`echo dump_cbor.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I.   -I/usr/local/ssl/include -I. -I..  -Qunused-arguments -pthread -g -O2 -MT dump_cbor.o -MD -MP -MF $depbase.Tpo -c -o dump_cbor.o dump_cbor.c &&\
	mv -f $depbase.Tpo $depbase.Po
dump_cbor.c:566:116: error: variable has incomplete type 'my_bpftimeval' (aka 'struct timeval')
  ...from, iaddr to, uint8_t proto, unsigned flags, unsigned sport, unsigned dport, my_bpftimeval ts, const u_char *p...
                                                                                                  ^
./dnscap_common.h:48:16: note: forward declaration of 'struct timeval'
typedef struct MY_BPFTIMEVAL my_bpftimeval;
               ^
./dnscap_common.h:46:24: note: expanded from macro 'MY_BPFTIMEVAL'
# define MY_BPFTIMEVAL timeval
                       ^
1 error generated.
make[2]: *** [dump_cbor.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

**Comment by jelu** [comment]
What OS, distribution and such?

Can you send the full configure and make output?

**Comment by vollkommenheit** [comment]
git submodule update --init
git status
./autogen.sh
# OpenSSL 1.1.0c-dev
export CPPFLAGS=' -I/usr/local/ssl/include'
./configure
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:43: installing './compile'
configure.ac:37: installing './missing'
plugins/pcapdump/Makefile.am: installing './depcomp'
./configure exists...
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking build system type... x86_64-apple-darwin15.6.0
checking host system type... x86_64-apple-darwin15.6.0
checking for ar... ar
checking the archiver (ar) interface... ar
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking how to convert x86_64-apple-darwin15.6.0 file names to x86_64-apple-darwin15.6.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin15.6.0 file names to toolchain format... func_convert_file_noop
checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
checking for objdump... no
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking whether gcc is Clang... yes
checking whether Clang needs flag to prevent "argument unused" warning when linking with -pthread... -Qunused-arguments
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for pcap_open_live in -lpcap... yes
checking pcap/pcap.h usability... yes
checking pcap/pcap.h presence... yes
checking for pcap/pcap.h... yes
checking for pcap_create... yes
checking for pcap_set_tstamp_precision... yes
checking for pcap_set_immediate_mode... yes
checking for pcap_set_tstamp_type... yes
checking for pcap_setdirection... yes
checking for sched_yield... yes
checking for pcap_open_offline_with_tstamp_precision... yes
checking for pcap_direction_t... yes
checking for ns_initparse in -lbind... no
checking for __ns_initparse in -lbind... yes
checking for res_mkquery in -lresolv... no
checking for __res_mkquery in -lresolv... yes
checking for dlopen in -ldl... yes
checking for cbor_parser_init in -ltinycbor... no
checking for ldns_wire2pkt in -lldns... yes
checking for sys/types.h... (cached) yes
checking for netinet/in.h... yes
checking for arpa/nameser.h... yes
checking for netdb.h... yes
checking for resolv.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for netdb.h... (cached) yes
checking for netinet/in.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking ldns/ldns.h usability... yes
checking ldns/ldns.h presence... yes
checking for ldns/ldns.h... yes
checking arpa/nameser_compat.h usability... yes
checking arpa/nameser_compat.h presence... yes
checking for arpa/nameser_compat.h... yes
checking cbor.h usability... no
checking cbor.h presence... no
checking for cbor.h... no
checking cbor/cbor.h usability... no
checking cbor/cbor.h presence... no
checking for cbor/cbor.h... no
checking for snprintf... yes
checking for setreuid... yes
checking for setresuid... no
checking for setregid... yes
checking for setresgid... no
checking for setegid... yes
checking for seteuid... yes
checking for ns_initparse... no
checking for __ns_initparse... yes
checking for ns_parserr... no
checking for __ns_parserr... yes
checking for ns_sprintrr... no
checking for __ns_sprintrr... yes
checking for ns_name_uncompress... no
checking for __ns_name_uncompress... yes
checking for p_rcode... no
checking for __p_rcode... yes
checking for __assertion_failed... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating plugins/Makefile
config.status: creating plugins/pcapdump/Makefile
config.status: creating plugins/rssm/Makefile
config.status: creating plugins/txtout/Makefile
config.status: creating src/config.h
config.status: src/config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

# with either Apple llvm-gcc (clang) 7.3 or 8.0
make -j2

Making all in src
/Library/Developer/CommandLineTools/usr/bin/make  all-am
depbase=`echo dump_cbor.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I.   -I/usr/local/ssl/include -I. -I..  -Qunused-arguments -pthread -g -O2 -MT dump_cbor.o -MD -MP -MF $depbase.Tpo -c -o dump_cbor.o dump_cbor.c &&\
	mv -f $depbase.Tpo $depbase.Po
depbase=`echo options.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I.   -I/usr/local/ssl/include -I. -I..  -Qunused-arguments -pthread -g -O2 -MT options.o -MD -MP -MF $depbase.Tpo -c -o options.o options.c &&\
	mv -f $depbase.Tpo $depbase.Po
dump_cbor.c:566:116: error: variable has incomplete type 'my_bpftimeval' (aka 'struct timeval')
  ...from, iaddr to, uint8_t proto, unsigned flags, unsigned sport, unsigned dport, my_bpftimeval ts, const u_char *pay...
                                                                                                  ^
./dnscap_common.h:48:16: note: forward declaration of 'struct timeval'
typedef struct MY_BPFTIMEVAL my_bpftimeval;
               ^
./dnscap_common.h:46:24: note: expanded from macro 'MY_BPFTIMEVAL'
# define MY_BPFTIMEVAL timeval
                       ^
1 error generated.
make[2]: *** [dump_cbor.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1



# with gcc (GCC) 5.3.0

make -j2
...
depbase=`echo dump_cbor.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I.   -I/usr/local/ssl/include -I. -I..  -pthread -g -O2 -MT dump_cbor.o -MD -MP -MF $depbase.Tpo -c -o dump_cbor.o dump_cbor.c &&\
	mv -f $depbase.Tpo $depbase.Po
sed -e 's,[@]PACKAGE_VERSION[@],1.2.0,g' \
        -e 's,[@]PACKAGE_URL[@],https://github.com/DNS-OARC/dnscap/issues,g' \
        -e 's,[@]PACKAGE_BUGREPORT[@],dnscap-users@dns-oarc.net,g' \
        < ./dnscap.1.in > dnscap.1
dump_cbor.c:566:116: error: parameter 7 (‘ts’) has incomplete type
 int output_cbor(iaddr from, iaddr to, uint8_t proto, unsigned flags, unsigned sport, unsigned dport, my_bpftimeval ts, const u_char *payload, size_t payloadlen) {
                                                                                                                    ^
make[2]: *** [dump_cbor.o] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

**Comment by jelu** [comment]
Can you try and add `#include <time.h>` to `dnscap_common.h` and see if that works?

I do not have an Apple OS to test from so :(

**Comment by vollkommenheit** [comment]
Yup, adding #include <sys/time.h> to dnscap_common.h got it fixed. Thanks.

BTW, there has always been this warning

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../src -I/usr/local/ssl/include -I. -I../../src -I../../isc -g -O2 -MT txtout.lo -MD -MP -MF .deps/txtout.Tpo -c txtout.c  -fno-common -DPIC -o .libs/txtout.o
txtout.c:165:41: warning: format specifies type 'long' but the argument has type '__darwin_suseconds_t' (aka 'int')
      [-Wformat]
        fprintf(out, "%10ld.%06ld", ts.tv_sec, ts.tv_usec);
                            ~~~~~              ^~~~~~~~~~
                            %06d
1 warning generated.

**Comment by jelu** [comment]
OK good, I will fix this in the week to come and see what I can do about the warning.

**Comment by vollkommenheit** [comment]
Just managed to rid of the warning above by changing the following line in ./plugins/txtout/txtout.c

`fprintf(out, "%10ld.%06ld", ts.tv_sec, ts.tv_usec);`
to
`fprintf(out, "%10ld.%06ld", ts.tv_sec, (long) ts.tv_usec);`

per https://stackoverflow.com/questions/24486615/warning-format-06d-expects-type-int-but-argument-5-has-type-suseconds

**Comment by jelu** [comment]
Hope you can test the develop branch, reopen this issue if it's still a problem.

**Comment by vollkommenheit** [comment]
The latest code resolves the two issues above on my box too.
