### ISSUE TITLE
dnscap v1.3 lost packet

### ISSUE THREAD

**Issue by yiyuandao** [DNS-OARC/dnscap#58]
Hi,

I try to use dnscap v1.3 to capture DNS message,   dnsperf  send packet at 200QPS on loopback interface.

dnscap and dnsperf  are in the same VM(1G, 1 core)
after 30 seconds, I compared the result with tcpdump, found that dnscap lost more than 1000 packets.
but tcpdump captured all the dns packets.

then I checked the source code,  and found the reason is function _callback(), pcap_thread.c , line 881 to line 896
the pcaplist->queue(define PCAP_THREAD_DEFAULT_QUEUE_SIZE  64) is too small,  and break the while loop, and the default callback_queue_mode is PCAP_THREAD_QUEUE_MODE_DROP, so the packet was dropped.

one temporary way is that increase the pcaplist->queue size,  I just try set it to 6400, and do the test again, all dns pcaket was captured by dnscap.
but what is the proper vaule for the queue size?

any ideals to sovle this?
Thank you.

**Comment by jelu** [comment]
I haven't had the time for this project in a while, there are a lot of
updates in the pipeline for the capturing parts, sorry for that.

Also haven't had time to add `-o` for things like that queue size.

I will look at this next week and see what I can quick fix, thanks for the
report!

**Comment by jelu** [comment]
As of 191efa5b2994e556357963fbd4cae198e17480d8 the threaded code is now default disabled and queue is not used anymore so please test it and see if it still misses packets, also there is `-o pcap_buffer_size=<bytes>` which you can set to help not miss packets.

**Comment by yiyuandao** [comment]
@jelu I test it with the default configuration, no pthread,  send dns messages at 25174 QPS.
It captured all the dns messages. Perfect!

Thank you.

**Comment by jelu** [comment]
Thanks, will prepare a release then.

**Comment by yiyuandao** [comment]
@jelu but when the system load is very high, it still lost packets.
eg. VM(1G, 1 core)
receiver:
```
tcpdump -i lo port 53 -s 0 -w d.pcap
dnscap -t 600 -w data/tt -m qun -S  -i lo -6 -T -f -N
```
sender with AVG   QPS: 52326
```
for i in {1..40}; do  dnsperf -s ::1 -d sample.dat -c 10 -S 60 -l 30 -q 100000 -t 0 & done|grep 'Queries sent' |awk  '{a+=$3} END {print a}'
```

dnsperf sent 1602304 dns message, and 1569796 captured by dnscap in 30 seconds.
maybe this is due  to the highly system load.

BTW, the -S option result is wrong:
```
total drops: 0
lo: 3204608 recv 65014 drop 3269622 total ptdrop 0
```

**Comment by jelu** [comment]
Yes, your basically running 3 processes at 100% on one core. Give it at least 4 cores (and hoping you have that physical also).

The `-S` is not wrong, but might need explanation. `total drop` is the amount dropped by pcap-thread, the drop on `lo` is the amount dropped by the Kernel.

Since your using `-w` and `-t` your are also interrupting processing and that may make you drop packets, try setting a high buffer size with `-o pcap_buffer_size=bytes` or skip `-t`.
