### ISSUE TITLE
error: Libtool library used but 'LIBTOOL' is undefined

### ISSUE THREAD

**Issue by wessels** [DNS-OARC/dnscap#6]
I'm no automake expert so I need help understanding this error:

$ git clone git@github.com:DNS-OARC/dnscap
Cloning into 'dnscap'...
remote: Counting objects: 722, done.
remote: Total 722 (delta 0), reused 0 (delta 0), pack-reused 721
Receiving objects: 100% (722/722), 241.15 KiB | 0 bytes/s, done.
Resolving deltas: 100% (394/394), done.
Checking connectivity... done.
$ cd dnscap
$ sh autogen.sh 
configure.ac:15: installing './ar-lib'
configure.ac:13: installing './compile'
configure.ac:14: installing './config.guess'
configure.ac:14: installing './config.sub'
configure.ac:7: installing './install-sh'
configure.ac:7: installing './missing'
plugins/pcapdump/Makefile.am:8: error: Libtool library used but 'LIBTOOL' is undefined
plugins/pcapdump/Makefile.am:8:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
plugins/pcapdump/Makefile.am:8:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
plugins/pcapdump/Makefile.am:8:   If 'LT_INIT' is in 'configure.ac', make sure
plugins/pcapdump/Makefile.am:8:   its definition is in aclocal's search path.
plugins/pcapdump/Makefile.am: installing './depcomp'
plugins/rssm/Makefile.am:9: error: Libtool library used but 'LIBTOOL' is undefined
plugins/rssm/Makefile.am:9:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
plugins/rssm/Makefile.am:9:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
plugins/rssm/Makefile.am:9:   If 'LT_INIT' is in 'configure.ac', make sure
plugins/rssm/Makefile.am:9:   its definition is in aclocal's search path.
plugins/txtout/Makefile.am:8: error: Libtool library used but 'LIBTOOL' is undefined
plugins/txtout/Makefile.am:8:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
plugins/txtout/Makefile.am:8:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
plugins/txtout/Makefile.am:8:   If 'LT_INIT' is in 'configure.ac', make sure
plugins/txtout/Makefile.am:8:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1

$ cat /etc/issue
Ubuntu 14.04.4 LTS \n \l

$ uname -a
Linux packet-pushers.com 4.5.3-x86_64-linode67 #3 SMP Tue May 10 10:22:44 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jelu** [comment]
Is `libtool` installed?

If it is please give me it's version along with `autoconf`'s and
`automake`'s.

**Comment by wessels** [comment]
My bad, libtool was not installed.

Worst. Error. Message. Ever.
