### ISSUE TITLE
./pcap-thread/pcap_thread.h:62:2: error: "No endian byte order define, please fix" etc.

### ISSUE THREAD

**Issue by vollkommenheit** [DNS-OARC/dnscap#65]
Getting the following after the Mar 9, 2017 commits:

make[3]: Nothing to be done for `all'.
depbase=`echo dnscap.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I.    -I. -I..   -g -O2 -MT dnscap.o -MD -MP -MF $depbase.Tpo -c -o dnscap.o dnscap.c &&\
	mv -f $depbase.Tpo $depbase.Po
depbase=`echo dump_dns.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I.    -I. -I..   -g -O2 -MT dump_dns.o -MD -MP -MF $depbase.Tpo -c -o dump_dns.o dump_dns.c &&\
	mv -f $depbase.Tpo $depbase.Po
In file included from dnscap.c:151:
./pcap-thread/pcap_thread.h:62:2: error: "No endian byte order define, please fix"
#error "No endian byte order define, please fix"
 ^
./pcap-thread/pcap_thread.h:69:2: error: "No little endian define, please fix"
#error "No little endian define, please fix"
 ^
./pcap-thread/pcap_thread.h:76:2: error: "No big endian define, please fix"
#error "No big endian define, please fix"
 ^
./pcap-thread/pcap_thread.h:230:26: error: duplicate member 'th_off'
                u_int8_t th_off:4;
                         ^
./pcap-thread/pcap_thread.h:227:26: note: previous declaration is here
                u_int8_t th_off:4;
                         ^
./pcap-thread/pcap_thread.h:231:26: error: duplicate member 'th_x2'
                u_int8_t th_x2:4;
                         ^
./pcap-thread/pcap_thread.h:226:26: note: previous declaration is here
                u_int8_t th_x2:4;
                         ^
5 errors generated.
make[3]: *** [dnscap.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

**Comment by jelu** [comment]
On what *NIX, distribution​ and version do you get this?

**Comment by vollkommenheit** [comment]
Same setup as in https://github.com/DNS-OARC/dnscap/issues/35

gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix

**Comment by vollkommenheit** [comment]
Got past those errors by pasting the chunk from http://debugjournal.tumblr.com/post/99661010362/missing-byteswaph-and-endianh-on-mac-os-x into ./src/pcap-thread/pcap_thread.h

**Comment by jelu** [comment]
Thanks, I will add some of that in a week or so and let you try again
before merge.

**Comment by jelu** [comment]
OS X endian should be fixed now, can you test latest pcap-thread:
```
git clone https://github.com/DNS-OARC/pcap-thread.git
cd pcap-thread/hexdump
sh autogen.sh
./configure
make
```

**Comment by vollkommenheit** [comment]
Yup, it compiled fine now. However, I'm getting these warnings during "make":

cp "./../pcap_thread.c" .
depbase=`echo pcap_thread.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I.    -Wall -I. -I./../ -Qunused-arguments -pthread -g -O2 -MT pcap_thread.o -MD -MP -MF $depbase.Tpo -c -o pcap_thread.o pcap_thread.c &&\
	mv -f $depbase.Tpo $depbase.Po
hexdump.c:58:38: warning: format specifies type 'unsigned long' but the argument has type '__darwin_suseconds_t' (aka 'int') [-Wformat]
            first->pkthdr.ts.tv_sec, first->pkthdr.ts.tv_usec,
                                     ^~~~~~~~~~~~~~~~~~~~~~~~
hexdump.c:85:38: warning: format specifies type 'unsigned long' but the argument has type '__darwin_suseconds_t' (aka 'int') [-Wformat]
            first->pkthdr.ts.tv_sec, first->pkthdr.ts.tv_usec,
                                     ^~~~~~~~~~~~~~~~~~~~~~~~
hexdump.c:109:32: warning: format specifies type 'unsigned long' but the argument has type '__darwin_suseconds_t' (aka 'int') [-Wformat]
            pkthdr->ts.tv_sec, pkthdr->ts.tv_usec,
                               ^~~~~~~~~~~~~~~~~~
hexdump.c:130:32: warning: format specifies type 'unsigned long' but the argument has type '__darwin_suseconds_t' (aka 'int') [-Wformat]
            pkthdr->ts.tv_sec, pkthdr->ts.tv_usec,
                               ^~~~~~~~~~~~~~~~~~
hexdump.c:493:43: warning: format specifies type 'unsigned long' but the argument has type '__darwin_suseconds_t' (aka 'int') [-Wformat]
            printf("%lu.%lu\n", t.tv_sec, t.tv_usec);
                        ~~~               ^~~~~~~~~
                        %d
5 warnings generated.
gcc -Wall -I. -I./../ -Qunused-arguments -pthread -g -O2  -O3 -march=native -flto -o hexdump hexdump.o pcap_thread.o  -lpcap
