### ISSUE TITLE
dnscap.c:401: error: 'PCAP_NETMASK_UNKNOWN' undeclared here (not in a function)

### ISSUE THREAD

**Issue by wessels** [DNS-OARC/dnscap#68]
Compiling dnscap-1.4.0 on FreeBSD (8.4):

$ make
Making all in src
make  all-recursive
Making all in test
depbase=`echo dnscap.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; gcc -DHAVE_CONFIG_H -I.     -I.  -I..     -g -O2 -MT dnscap.o -MD -MP -MF $depbase.Tpo -c -o dnscap.o dnscap.c && mv -f $depbase.Tpo $depbase.Po
dnscap.c:398: warning: integer constant is too large for 'long' type
dnscap.c:401: error: 'PCAP_NETMASK_UNKNOWN' undeclared here (not in a function)
*** Error code 1

Stop in tmp/dnscap-1.4.0/src.

**Comment by jelu** [comment]
FreeBSD 8.4 is quite old... upgrade?

What libpcap version do you have?

**Comment by wessels** [comment]
libpcap-1.0.0.  Understood if FreeBSD-8.x is not supported by this version.  Is there a way to find out which OS versions the release has been verified against?

**Comment by jelu** [comment]
It's tested against the latest stable Debian, Ubuntu, CentOS, FreeBSD and
OpenBSD (current version numbers should be 8, 16.04, 7, 11.0 and 6.0) using
Jenkins (https://dev.dns-oarc.net/jenkins/) and I try to keep them
up-to-date as good as I can.
