### ISSUE TITLE
Update plugin for RSSAC002v3

### ISSUE THREAD

**Issue by jelu** [DNS-OARC/dnscap#91]
The RSSM plugin was developed based on the first RSSAC002 document and has not been updated since.

This deliverable will update the plugin to the latest document RSSAC002v3 and create plugin specific tests.

**Comment by jelu** [comment]
@wessels There is an undocumented change in the v3 specification.

Section 2 for v1/v2 says:
```
Only syntactically correct DNS messages should be counted. Data-less connections and
invalid, malformed, short, or non-DNS messages should not be counted.
```
But v3 changed to:
```
Only syntactically correct DNS messages should be counted. Data-less connections or
non-DNS messages should not be counted.
```
Is this correctly assumed that invalid, malformed and cut-off DNS messages should be counted?

**Comment by jelu** [comment]
@wessels I'll send this question and more to the RSSAC group

**Comment by wessels** [comment]
As I recall, the change of text around non-DNS messages was only to simplify the language there, but not to alter the intention of what to count.  In other words, "invalid", "short" and "malformed" are redundant because they are all already "non-dns" messages.

**Comment by jelu** [comment]
So that would mean drop truncated (short) DNS message?

This would have quite huge impact on RSSM plugin because dnscap regards anything that is enough for a DNS header (NOTE: not valid DNS, just enough bytes for the header) as a DNS message.

To comply with the specification the RSSM plugin would need to parse and validate all DNS messages it receives and drop anything that isn't completely valid full-length DNS message.

**Comment by raybellis** [comment]
There are some potential shortcuts.   A legal query cannot be less than 17 bytes (12 bytes header, '.', 2 byte QTYPE, 2 byte QCLASS).   It also can't have a QDCOUNT > 1, and there are limits to the feasible upper bounds on the other section counters.

In part this change was put there to allow for other systems (i.e. BIND's stats channel) that don't count malformed packets.   Personally I think the "should" in the revised text gives enough latitude that minimal sanity checks without full parsing would suffice.

**Comment by raybellis** [comment]
Also, if QR == 0 && OPCODE == QUERY, then ANCOUNT, NSCOUNT and ARCOUNT must == 0.

Catching those conditions would drop a lot of any random garbage that happens to hit a server without fully parsing the packet.

**Comment by jelu** [comment]
@raybellis But malformed packets was never counted.

If the general consensus about "should" is as you describe then you could really just remove the whole sentence since the next sentence says `non-DNS messages should not be counted`.
