### ISSUE TITLE
Multiple plugin support - documentation issue

### ISSUE THREAD

**Issue by raybellis** [DNS-OARC/dnscap#97]
The documentation currently leads people to believe that it's only possible to have one plugin specified because that plugin will consume all following options:

>    `-P plugin.so` ...
>       Load and use the specified plugin. Any options given after this are sent to the plugin.

In fact, so long as the plugin uses `getopt()` it is possible to break out of the plugin's argument processing by supplying `--` as an option, at which point control returns back to the main argument processing loop, e.g.:

    dnscap -P <plugin1.so> <args...> -- -P <plugin2.so> <args....> -- <normal args...>

**Comment by jelu** [comment]
Fixed in #249
